cara/cara/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),

    path('login/', auth_views.LoginView.as_view(
    template_name='registration/login.html',  
    extra_context={ 
        'next': '/', 
    },
    ), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name="registration/logout.html"), name="logout"),
    path('password-reset/', auth_views.PasswordResetView.as_view(), name="password_reset"),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cara/store/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.store, name="store"),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('blog/', views.NormalBlogListView.as_view(template_name="store/blog.html"), name='blog'),
    path('cart/', views.cart, name="cart"),
    path('checkout/', views.checkout, name="checkout"),
    path('update_item/', views.updateItem, name="update_item"),
    path('process_order/', views.processOrder, name="process_order"),


	path('register/', views.register, name='register'),
	path('dashboard/', views.user_dashboard, name='user_dashboard'),

	path('add_product/', views.add_product, name='add_product'),
  path('shop/', views.CustomerProductListView.as_view(template_name="store/shop.html"), name='shop'),
  path('products/<int:pk>/', views.productdetail, name='productdetail'),


	path('unauthorized/', views.unauthorized, name="unauthorized"),

  # ADMIN ROUTES
  path('view_products/', views.ProductListView.as_view(template_name="admin/product_list.html"), name="product_list"),
	path('products/<pk>/detail', views.ProductDetailView.as_view(template_name="admin/product_detail_view.html"), name="product_detail_view"),
	path('products/<pk>/update', views.ProductUpdateView.as_view(template_name="admin/product_update_form.html"), name="product_update_form"),
	path('products/<pk>/delete', views.ProductDeleteView.as_view(template_name="admin/product_delete_form.html"), name="product_delete_form"),
	path('view_customers/', views.CustomerListView.as_view(template_name="admin/customers_list.html"), name="customers_list"),
	path('view_orders/', views.OrderListView.as_view(template_name="admin/orders_list.html"), name="orders_list"),

  # ADMIN BLOG ROUTES
  path('all-blogs/', views.BlogListView.as_view(template_name="admin/blog_list.html"), name="blog_list"),
	path('blog/<slug>/detail', views.BlogDetailView.as_view(template_name="admin/blog_detail_view.html"), name="blog_detail_view"),
	path('blog/<slug>/delete', views.BlogDeleteView.as_view(template_name="admin/blog_delete_form.html"), name="blog_delete_form"),
	path('blog/<slug>/update', views.BlogUpdateView.as_view(template_name="admin/blog_update_form.html"), name="blog_update_form"),
	path('blog/add-blog/', views.add_blog, name='add_blog'),


  path ('admin-user/dashboard', views.admin_dashboard, name='admin_dashboard')
]

cara/store/models.py
from secrets import choice
from statistics import mode

from django.contrib.auth.models import User
from django.db import models
from multiselectfield import MultiSelectField

# Create your models here.

class Customer(models.Model):
	user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
	name = models.CharField(max_length=200, null=True, default="admin")
	email = models.CharField(max_length=200, default="admin@admin.com")

	def __str__(self):
		return self.name


class Product(models.Model):
	SKINCARE="skincare"
	PRODUCT_TAGS = (
		(SKINCARE, "Skin Care"),
		("makeup", "Makeup"),
		("bath&body", "Bath & Body")
	)
	name = models.CharField(max_length=200)
	tag= models.CharField(max_length=100, choices=PRODUCT_TAGS,default=SKINCARE,null=True,blank=True)
	price = models.FloatField()
	description = models.TextField()
	image = models.ImageField(null=True, blank=True)

	def __str__(self):
		return self.name

	@property
	def imageURL(self):
		try:
			url = self.image.url
		except:
			url = ''
		return url

class Order(models.Model):
	customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
	date_ordered = models.DateTimeField(auto_now_add=True)
	complete = models.BooleanField(default=False)
	transaction_id = models.CharField(max_length=100, null=True)

	def __str__(self):
		return str(self.id)
		
	@property
	def shipping(self):
		shipping = False
		orderitems = self.orderitem_set.all()
		for i in orderitems:
			
				shipping = True
		return shipping

	@property
	def get_cart_total(self):
		orderitems = self.orderitem_set.all()
		total = sum([item.get_total for item in orderitems])
		return total 

	@property
	def get_cart_items(self):
		orderitems = self.orderitem_set.all()
		total = sum([item.quantity for item in orderitems])
		return total 

class OrderItem(models.Model):
	product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
	order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
	quantity = models.IntegerField(default=0, null=True, blank=True)
	date_added = models.DateTimeField(auto_now_add=True)

	@property
	def get_total(self):
		product = self.product
		total = product.price * self.quantity
		return total

class ShippingAddress(models.Model):
	customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True)
	order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
	address = models.CharField(max_length=200, null=False)
	city = models.CharField(max_length=200, null=False)
	state = models.CharField(max_length=200, null=False)
	zipcode = models.CharField(max_length=200, null=False)
	date_added = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.address

class Blog(models.Model):
	BLOG_TAGS = (
		("design", "Design"),
		("fashion", "Fashion")
	)
	SKIN_TYPES = (
	(	'normal', "Normal"),
	('combination', 'Combination'),
	('oily', "Oily")
	)
	SKINCARE_CONCERNS = (
		('dullness', 'Dullness'),
		("uneventexture",'Uneven Texture'),
		('acne', 'Acne'),
		('blemishes','Blemishes')
	)
	FORMULATION = (
		('liquid', "Liquid"),
	)
	HIGHLIGHTED_INGREDIENTS = (
	('ga','Glycolic Acid'),
	('la','Lactic Acid'),
	('sa','Salicylic Acid'),
	)

	user = models.ForeignKey(User, on_delete=models.CASCADE)
	title = models.CharField(max_length=200, null=False)
	description = models.TextField()
	tag= models.CharField(max_length=10, choices=BLOG_TAGS)
	slug = models.SlugField(unique=True, max_length=100)
	published_at = models.DateField(auto_now_add=True)
	image = models.ImageField(null=True, blank=True)
	skin_type = MultiSelectField(choices=SKIN_TYPES, min_choices=1)
	highlighted_ingredients = MultiSelectField(choices=HIGHLIGHTED_INGREDIENTS, min_choices=1)
	skincare_concerns = MultiSelectField(choices=SKINCARE_CONCERNS, min_choices= 1)
	formulation = models.CharField(max_length=10, choices=FORMULATION)


	def __str__(self):
		return self.title
	
	@property
	def imageURL(self):
		try:
			url = self.image.url
		except:
			url = ''
		return url

cara/store/forms.py
from dataclasses import field

from crispy_forms.helper import FormHelper, Layout
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Blog, Product


# REF: https://www.crunchydata.com/blog/building-a-user-registration-form-with-djangos-built-in-authentication
class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=100, help_text='First Name')
    last_name = forms.CharField(max_length=100, help_text='Last Name')

    class Meta:
        model = User
        fields = ["first_name", "last_name","username", "password1", "password2",  "email"]

class AddProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ["name", "price", "description", "image", 'tag']

class AddBlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'description', 'tag', 'image', 'skin_type','highlighted_ingredients','highlighted_ingredients','skincare_concerns','formulation']

cara/store/views.py
import datetime
import json
from random import choice

from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.template.defaultfilters import slugify
from django.utils.decorators import method_decorator
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView, UpdateView
from django.views.generic.list import ListView

from .forms import AddBlogForm, AddProductForm, RegisterForm
from .models import *
from .models import Customer
from .utils import cartData, guestOrder


def about(request):
   return render(request, 'store/about.html')

def contact(request):
   return render(request, 'store/contact.html')


class NormalBlogListView(ListView):
	paginate_by = 10
	model = Blog
	filter = ['published_by']
	
	
def blog(request):
   return render(request, 'store/blog.html')
   
def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            email = form.cleaned_data.get('email')
            user = authenticate(username = username, password = password)
            customer = Customer(user = user, name=username, email=email)
            customer.save()
            login(request, user)
            return redirect('store')
    else:
        form = RegisterForm()
    return render(request, 'registration/register.html', {'form': form})

def unauthorized(request):
	return render(request, "store/unauthorized.html")

def store(request):
	data = cartData(request)

	cartItems = data['cartItems']
	order = data['order']
	items = data['items']

	products = Product.objects.all()
	context = {'products':products, 'cartItems':cartItems}
	return render(request, 'store/store.html', context)

def productdetail(request,pk):
	product = Product.objects.get(id = pk)
	# Ref: https://stackoverflow.com/questions/22816704/django-get-a-random-object
	pks = Product.objects.values_list('pk', flat=True)
	random_pks = [choice(pks), choice(pks), choice(pks), choice(pks)]
	random_products = Product.objects.filter(id__in= random_pks)

	data = cartData(request)

	cartItems = data['cartItems']


	return render(request, 'store/product.html', {'product': product, 'others': random_products, 'cartItems': cartItems})


def cart(request):
	data = cartData(request)

	cartItems = data['cartItems']
	order = data['order']
	items = data['items']


	context = {'items':items, 'order':order, 'cartItems':cartItems}
	return render(request, 'store/cart.html', context)

def checkout(request):
	data = cartData(request)
	
	cartItems = data['cartItems']
	order = data['order']
	items = data['items']

	context = {'items':items, 'order':order, 'cartItems':cartItems}
	return render(request, 'store/checkout.html', context)

def updateItem(request):
	data = json.loads(request.body)
	productId = data['productId']
	action = data['action']


	customer = request.user.customer
	product = Product.objects.get(id=productId)
	order, created = Order.objects.get_or_create(customer=customer, complete=False)

	orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)

	if action == 'add':
		orderItem.quantity = (orderItem.quantity + 1)
	elif action == 'remove':
		orderItem.quantity = (orderItem.quantity - 1)

	orderItem.save()

	if orderItem.quantity <= 0:
		orderItem.delete()

	return JsonResponse('Item was added', safe=False)

def processOrder(request):
	transaction_id = datetime.datetime.now().timestamp()
	data = json.loads(request.body)

	if request.user.is_authenticated:
		customer = request.user.customer
		order, created = Order.objects.get_or_create(customer=customer, complete=False)
	else:
		customer, order = guestOrder(request, data)

	total = float(data['form']['total'])
	order.transaction_id = transaction_id

	if total == order.get_cart_total:
		order.complete = True
	order.save()

	if order.shipping == True:
		ShippingAddress.objects.create(
		customer=customer,
		order=order,
		address=data['shipping']['address'],
		city=data['shipping']['city'],
		state=data['shipping']['state'],
		zipcode=data['shipping']['zipcode'],
		)

	return JsonResponse('Payment submitted..', safe=False)

def add_product(request):
	if request.user.is_superuser:
		if request.method == "POST":
			form = AddProductForm(request.POST, request.FILES)
			if form.is_valid():
				form.save()
				return redirect('/')
		else:
			form = AddProductForm()

		return render(request, "admin/add_product.html",{
			'form':form
		})
	return redirect('unauthorized')

class CustomerProductListView(ListView):
	model = Product
	paginate_by = 4

	# REF: https://stackoverflow.com/questions/13416502/django-search-form-in-class-based-listview
	def get_queryset(self):
		query = self.request.GET.get('q')

		if query:
			objects = self.model.objects.filter(Q(name__icontains=query) | Q(tag__icontains=query))
		else:
			objects = self.model.objects.all()
		return objects


class ProductListView(LoginRequiredMixin, ListView):
	login_url = "/login/"
	model = Product
	paginate_by = 4
class ProductDetailView(LoginRequiredMixin, DetailView):
	login_url = "/login/"
	model = Product
	paginate_by = 4

class ProductUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
	login_url = "/login/"
	model = Product
	fields = ["name", "price", "description",  "image", 'tag']
	template_name_suffix: str = "_update_form"
	success_url = '/view_products/'
	success_message = "Product updated successfully"

class ProductDeleteView(LoginRequiredMixin,SuccessMessageMixin, DeleteView):
	login_url = "/login/"
	model = Product
	success_url = "/view_products/"
	success_message = "Deleted Product Successfully"


class OrderListView(LoginRequiredMixin, ListView):
	login_url = "/login/"
	model = Order
	paginate_by = 10


class CustomerListView(LoginRequiredMixin, ListView):
	login_url = "/login/"
	model = Customer
	paginate_by = 10


######### BLOG SECTION #########
class BlogListView(LoginRequiredMixin, ListView):
	login_url = "/login/"
	model= Blog
	paginate_by = 10


class BlogDetailView(LoginRequiredMixin, DetailView):
	login_url = "/login/"
	model= Blog
	
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		return context

class BlogDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
	login_url = "/login/"
	model = Blog
	success_url = "/all-blogs/"
	success_message = "Deleted Blog Successfully"

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		return context


def add_blog(request):
	if request.user.is_superuser:
		if request.method == "POST":
			form = AddBlogForm(request.POST, request.FILES)
			print(form)
			if form.is_valid():
				newpost = form.save(commit=False)
				newpost.user = request.user
				newpost.slug = slugify(newpost.title)
				newpost.save()
				form.save_m2m()
				return redirect('/all-blogs/')
		else:
			form = AddBlogForm()
		return render(request, "admin/add_blog.html",{
			'form':form
		})
	return redirect('unauthorized')


class BlogUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
	login_url = "/login/"
	model = Blog
	fields = ["title", "tag", "description", "image", 'skin_type','highlighted_ingredients','highlighted_ingredients','skincare_concerns','formulation']
	template_name_suffix: str = "_update_form"
	success_url = '/all-blogs/'
	success_message = "Updated Blog Successfully"


@login_required(login_url='/login/')
def admin_dashboard(request):
	if request.user.is_superuser:
		blog_count = Blog.objects.count()
		customers_count = Customer.objects.count()
		orders_count = Order.objects.count()
		products_count = Product.objects.count()
		context = {
			"blog_count": blog_count,
			"customers_count": customers_count,
			"orders_count": orders_count,
			"products_count": products_count
		}
		return render(request, "admin/dashboard.html",context)
	else:
		return redirect('unauthorized')


@login_required(login_url='/login/')
def user_dashboard(request):
	customer = Customer.objects.get(user=request.user)
	orders_count = Order.objects.filter(customer=customer)
	context = {
		"orders": orders_count,
		"customer": customer
	}
	return render(request, "store/dashboard.html",context)

cara/store/templates/store/product.html
{% extends "base/index.html" %}
{% block content %}
{% load static %}
<section id="prodetails" class="section-p1">
  <div class="single-pro-img">
    <img src="{{product.imageURL}}" width="100%" id="MainImg" alt="" />

    <div class="small-img-group">
      <div class="small-img-col">
        <img
          src="/static/images/products/f1.jpg"
          width="100%"
          class="small-img"
          alt=""
        />
      </div>
      <div class="small-img-col">
        <img
          src="/static/images/products/f2.jpg"
          width="100%"
          class="small-img"
          alt=""
        />
      </div>
      <div class="small-img-col">
        <img
          src="/static/images/products/f3.jpg"
          width="100%"
          class="small-img"
          alt=""
        />
      </div>
      <div class="small-img-col">
        <img
          src="/static/images/products/f4.jpg"
          width="100%"
          class="small-img"
          alt=""
        />
      </div>
    </div>
  </div>

  <div class="single-pro-details">
    <h6>{{ product.get_tag_display }}</h6>
    <h4>{{product.name}}</h4>
    <h2>$ {{product.price}}</h2>
    <button data-product="{{product.id}}" data-action="add" class="normal add-btn update-cart">Add to Cart</button>
    <h4>Product Details</h4>
    <span>
      {{product.description}}  
    </span
    >
  </div>
</section>

<section id="product1" class="section-p1">
  <h2>Featured Products</h2>
  <p>Popular Categories Collection</p>
  <div class="pro-container">
    {% for product in others %}
        <a class="pro" href="{% url 'productdetail' product.id %}" style="text-decoration: none;">
          <img src="{{product.imageURL}}"/>
          <div class="des">
            <div class="product_container">
            <span>{{ product.get_tag_display }}</span>
            <h5>
              {{ product.name }}
            </h5>
            <div class="star">
              <i class="fas fa-star"></i>
              <i class="fas fa-star"></i>
              <i class="fas fa-star"></i>
              <i class="fas fa-star"></i>
              <i class="fas fa-star-half"></i>
            </div>
            <h4>$ {{ product.price }}</h4>
            </div>
            <div class="button_container">
              <button data-product="{{product.id}}" data-action="add" class="cart update-cart"><i class="fas fa-shopping-cart "></i></button>
            </div>
          </div>
        </a>
      {% endfor %}
  </div>
</section>

<section id="newsletter" class="section-p1 section-m1">
  <div class="newstext">
    <h4>Sign Up For Newsletter</h4>
    <p>
      Get E-mail updates about our latest shop and
      <span>special offers.</span>
    </p>
  </div>
  <div class="form">
    <input type="text" placeholder="Your email address" />
    <button class="normal">Sign Up</button>
  </div>
</section>
{% endblock %}

cara/store/templates/store/shop.html
{% extends "base/index.html" %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Cara</title>
    <link
      rel="stylesheet"
      href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
    />
    <link rel="stylesheet" href="style.css" />
  </head>
  <body>
    <section id="page-header">
      <h2>#stayhome</h2>
      <p>Stay tuned for seasonal sales!</p>
    </section>
    <section class="section-p1">
      <h5 class="mb-3">Search for products</h5>
      <form class="d-flex my-2 my-lg-0" method="GET">
        <input class="form-control mr-sm-2 w-100" name="q" type="search" placeholder="Search" aria-label="Search" value="{{ request.GET.q }}">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </section>

    <section id="product1" class="section-p1">
      <div class="pro-container">
        {% for product in object_list %}
          <a class="pro" href="{% url 'productdetail' product.id %}" style="text-decoration: none;">
            <img src="{{product.imageURL}}"/>
            <div class="des">
              <div class="product_container">
              <span>{{ product.get_tag_display }}</span>
              <h5>{{ product.name }}</h5>
              <div class="star">
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star-half"></i>
              </div>
              <h4>$ {{ product.price }}</h4>
              </div>
              <div class="button_container">
                <button data-product="{{product.id}}" data-action="add" class="cart update-cart"><i class="fas fa-shopping-cart "></i></button>
              </div>
            </div>
          </a>
        {% empty %}
        <p style="margin-top: -80px;" class="text-center">Sorry, no product for <strong>{{request.GET.q}}</strong> found. Try searching with another keyword</p>
        {% endfor %}
        </div>

        <div>
          <div class="d-flex justify-content-between align-items-center">
      <h3 class="mt-4">New Arrivals</h3>
      <p>Cosrx Now in Stock!</p>
          </div>

      <div class="pro-container">
        {% for product in object_list %}
        <a class="pro" href="{% url 'productdetail' product.id %}" style="text-decoration: none;">
          <img src="{{product.imageURL}}"/>
          <div class="des">
            <div class="product_container">
            <span>{{ product.get_tag_display }}</span>
            <h5>{{ product.name }}</h5>
            <div class="star">
              <i class="fas fa-star"></i>
              <i class="fas fa-star"></i>
              <i class="fas fa-star"></i>
              <i class="fas fa-star"></i>
              <i class="fas fa-star-half"></i>
            </div>
            <h4>$ {{ product.price }}</h4>
            </div>
            <div class="button_container">
              <button data-product="{{product.id}}" data-action="add" class="cart update-cart"><i class="fas fa-shopping-cart "></i></button>
            </div>
          </div>
        </a>
        {% empty %}
        <p style="margin-top: -20px;">Sorry, no product for <strong>{{request.GET.q}}</strong> found. Try searching with another keyword</p>
      {% endfor %} 
      </div>
    </section>
  {% include "base/pagination.html" %}
    <section id="newsletter" class="section-p1 section-m1">
      <div class="newstext">
        <h4>Sign Up For Newsletter</h4>
        <p>
          Get E-mail updates about our latest shop and
          <span>special offers.</span>
        </p>
      </div>
      <div class="form">
        <input type="text" placeholder="Your email address" />
        <button class="normal">Sign Up</button>
      </div>
    </section>
  </body>
</html>
{% endblock %}

cara/store/templates/store/store.html
{% extends "base/index.html" %}
{% block content %}
{% load static %}
    <section id="hero">
      <h4>Discover the latest in beauty at Cara!</h4>
      <h2>Super deals</h2>
      <h1>On all products</h1>
      <p>
        Explore an unrivaled selection of makeup,<br />
        skincare & more from classic & emerging brands.
      </p>
      <button>Shop now</button>
    </section>
    <section id="feature" class="section-p1">
      <div class="fe-box">
        <img src="{% static 'images/features/f1.png' %}" alt="" />
        <h6>Free Shipping</h6>
      </div>
      <div class="fe-box">
        <img src="{% static 'images/features/f2.png' %}" alt="" />
        <h6>Online order</h6>
      </div>
      <div class="fe-box">
        <img src="{% static 'images/features/f3.png' %}" alt="" />
        <h6>Save Money</h6>
      </div>
      <!-- <div class="fe-box">
        <img src="images/features/f4.png" alt="" />
        <h6>Sales</h6>
      </div> -->
      <div class="fe-box">
        <img src="{% static 'images/features/f5.png' %}" alt="" />
        <h6>Happy Sell</h6>
      </div>
      <div class="fe-box">
        <img src="{% static 'images/features/f6.png' %}" alt="" />
        <h6>F24/7 Support</h6>
      </div>
    </section>

    <section id="product1" class="section-p1">
      <h2>Featured Products</h2>
      <p>Popular Categories Collection</p>
      <div class="pro-container">
      {% for product in products %}
        <a class="pro" href="{% url 'productdetail' product.id %}" style="text-decoration: none;">
          <img src="{{product.imageURL}}"/>
          <div class="des">
            <div class="product_container">
            <span>{{ product.get_tag_display }}</span>
            <h5>{{ product.name }}</h5>
            <div class="star">
              <i class="fas fa-star"></i>
              <i class="fas fa-star"></i>
              <i class="fas fa-star"></i>
              <i class="fas fa-star"></i>
              <i class="fas fa-star-half"></i>
            </div>
            <h4>$ {{ product.price }}</h4>
            </div>
            <div class="button_container">
              <button data-product="{{product.id}}" data-action="add" class="cart update-cart"><i class="fas fa-shopping-cart "></i></button>
            </div>
          </div>
        </a>
      {% endfor %}
      </div>
    </section>

    <section id="banner" class="section-m1">
      <h4>Repair Services</h4>
      <h2>Up to <span>70% off</span>All T-shirts & Accessories</h2>
      <button class="normal">Explore More</button>
    </section>

    <section id="product1" class="section-p1">
      <h2>New Arrivals</h2>
      <p>Cosrx Now in Stock!</p>
      <div class="pro-container">
        {% for product in products %}
          <a class="pro" href="{% url 'productdetail' product.id %}" style="text-decoration: none;">
            <img src="{{product.imageURL}}"/>
            <div class="des">
              <div class="product_container">
              <span>{{ product.get_tag_display }}</span>
              <h5>{{ product.name }}</h5>
              <div class="star">
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star-half"></i>
              </div>
              <h4>$ {{ product.price }}</h4>
              </div>
              <div class="button_container">
                <button data-product="{{product.id}}" data-action="add" class="cart update-cart"><i class="fas fa-shopping-cart "></i></button>
              </div>
            </div>
          </a>
        {% endfor %}
        </div>
    </section>

    <section id="sm-banner" class="section-p1">
      <div class="banner-box">
        <h2>Deals we love</h2>
        <span>The perfect size palette is on sale at Cara!</span>
        <button class="white">Learn More</button>
      </div>
      <div class="banner-box banner-box2">
        <h2>Upcoming products</h2>
        <span>Fenty Skin available soon at Cara</span>
        <button class="white">Collection</button>
      </div>
    </section>

    <section id="banner3">
      <div class="banner-box">
        <h3>SEASONAL SALE</h3>
        <h2>Sephora Favorites Collection -50% OFF</h2>
      </div>
      <div class="banner-box banner-box2">
        <h3>NEW SKINCARE COLLECTION</h3>
        <h2>KRAVEBEAUTY</h2>
      </div>
      <div class="banner-box banner-box3">
        <h3>rhode</h3>
        <h2>New minimalist skincare line</h2>
      </div>
    </section>

    <section id="newsletter" class="section-p1 section-m1">
      <div class="newstext">
        <h4>Sign Up For Newsletter</h4>
        <p>
          Get E-mail updates about our latest shop and
          <span>special offers.</span>
        </p>
      </div>
      <div class="form">
        <input type="text" placeholder="Your email address" />
        <button class="normal">Sign Up</button>
      </div>
    </section>
</html>
{% endblock %}